### ISSUE TITLE
Fix the rgb video fps in dummy_camera node

### ISSUE THREAD

**Issue by vieiramanoel** [unball/ieee-very-small#42]
For some reason the line "ros::Rate loop_rate(rgb_cap.get(CV_CAP_PROP_FPS));" is making ROS throw the exeption "Time is out of dual 32-bit range".

**Comment by georgebrindeiro** [comment]
Check the return type of rgb_cap.get(), might be 64 bit

**Comment by gabrielnaves** [comment]
For some reason, "rgb_cap.get(CV_CAP_PROP_FPS)" is giving "-nan".
This bug is fixed when manually setting the fps: "ros::Rate loop_rate(25);" (25 is the fps of the video).
Since this issue has "blocker" priority, I'm going to set the fps manually.
This issue will continue with "minor" priority.

**Comment by gabrielnaves** [comment]
Update: This problem was caused by the video file. For some reason it had its fps data corrupted.
The dummy_camera node now identifies when the video file's fps info is corrupted (which gives a NaN fps value), and uses fps = 25 instead.
If the frame rate data is valid, it uses the original frame rate.
