### ISSUE TITLE
Create trajectory controller.

### ISSUE THREAD

**Issue by matheusportela** [unball/ieee-very-small#52]
Explained in #49.

**Comment by imota** [comment]
About this class and the explanation in #49 , it was said to iterate through all robots when calculating forces. My thought is, wouldn't it be better if this class only dealt with a single robot at a time? Because then it would not have to know how many robots we have. I just think it would reduce coupling. I haven't thought of implementation details yet because I haven't seen the state of the code, but this is worth thinking.

**Comment by matheusportela** [comment]
Yeah, it's probably better
